### ISSUE TITLE
Unable to generate native Image with Quarkus 3.19.1 and OpenTelemetry

### ISSUE THREAD

**Issue by DSkoufis** [quarkiverse/quarkus-amazon-services#1604]
Original issue in Quarkus: https://github.com/quarkusio/quarkus/issues/46540

Reproducer [here](https://github.com/DSkoufis/quarkus-otel-lambda/tree/27244ac323b1b026a530d27c755f78510820f8f3)

### Expected behavior

Native build to work

### Actual behavior

Not working with latest Quarkus version 3.19.1

### How to Reproduce?

```shell
mvn verify -Dnative -Dquarkus.native.container-build=true
```

### Output

```
Error: Substitution target for io.quarkus.amazon.common.runtime.Alias_Response is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
  com.oracle.svm.core.util.UserError$UserException: Substitution target for io.quarkus.amazon.common.runtime.Alias_Response is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
  	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1086)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:373)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:351)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1029)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:907)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:590)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
```

### Notes

[`io.opentelemetry.instrumentation.awssdk.v2_2.Response` has been moved to `io.opentelemetry.instrumentation.awssdk.v2_2.internal.Response` with v2.9.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/9a7f7125ab3f77c47a46be524f29e150536fba6f#diff-c140aa234c2eaf08db14f8a6ebb62f73a4529487a2b92f494962ddee377ed1fe)

quarkus-amazon-services still modifies the [old class](https://github.com/quarkiverse/quarkus-amazon-services/blob/564fa050b05e978517cf9c24f74134f1e1989a2b/common/runtime/src/main/java/io/quarkiverse/amazon/common/runtime/OtelSubstitutions.java#L72)

**Comment by scrocquesel** [comment]
Fixed in 3.3.0

**Comment by DSkoufis** [comment]
@scrocquesel I've tried using `io.quarkiverse.amazonservices:quarkus-amazon-services-bom:3.3.0` and quarkus 3.19.2 with a new commit in the reproducer [linked here](https://github.com/DSkoufis/quarkus-otel-lambda/tree/ea1a6c5165233167a33bfe7a8d8e6eda543c65b6) but I'm still getting an error:

```
[1/8] Initializing...                                                                                    (0.0s @ 0.16GB)
Error: One of @Delete, @Alias, or @Inject must be used: final io.quarkiverse.amazon.common.runtime.OtelNewSubstitutions io.quarkiverse.amazon.common.runtime.OtelNewSubstitutions$Alias_Response.this$0
com.oracle.svm.core.util.UserError$UserException: One of @Delete, @Alias, or @Inject must be used: final io.quarkiverse.amazon.common.runtime.OtelNewSubstitutions io.quarkiverse.amazon.common.runtime.OtelNewSubstitutions$Alias_Response.this$0
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.guarantee(UserError.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:519)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:428)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:395)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:351)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1029)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:907)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:590)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
```

**Comment by scrocquesel** [comment]
Thank you for reporting this. Unfortunately, it only happens when the project does not have an SQS/SNS dependency, which our integration tests do have.

**Comment by DSkoufis** [comment]
Thank you @scrocquesel for fixing it
